(define (problem transporation_problem)
  (:domain transportation_domain)
  (:objects 
	person - Person
	kista sdbyberg vskogen tc omalm uni ropsten ljholmen fruangen skarhlmn kungstrad karlberg karlstrnd nybroplan rosenlund alvsjo frosunda skyttehlm - Node)
  (:init 
  (= (total-cost) 0)

	(Metroline kista vskogen) (Metroline vskogen kista)
	(Metroline sdbyberg vskogen) (Metroline vskogen sdbyberg)
	(Metroline vskogen tc) (Metroline tc vskogen)
	(Metroline tc kungstrad) (Metroline kungstrad tc)
	(Metroline ropsten omalm) (Metroline omalm ropsten)
	(Metroline uni omalm) (Metroline omalm uni)
	(Metroline omalm tc) (Metroline tc omalm)
	(Metroline tc ljholmen) (Metroline ljholmen tc)
	(Metroline ljholmen fruangen) (Metroline fruangen ljholmen)
	(Metroline ljholmen skarhlmn) (Metroline skarhlmn ljholmen)

	(Busline kista frosunda) (Busline kista frosunda)
	(Busline skyttehlm frosunda) (Busline frosunda skyttehlm)
	(Busline vskogen skyttehlm) (Busline skyttehlm vskogen)
	(Busline vskogen karlberg) (Busline karlberg vskogen)
	(Busline karlberg karlstrnd) (Busline karlstrnd karlberg)
	(Busline karlstrnd omalm) (Busline omalm karlstrnd)
	(Busline omalm nybroplan) (Busline nybroplan omalm)
	(Busline nybroplan kungstrad) (Busline kungstrad nybroplan)
	(Busline kungstrad rosenlund) (Busline rosenlund kungstrad)
	(Busline rosenlund ljholmen) (Busline ljholmen rosenlund)
	(Busline ljholmen alvsjo) (Busline alvsjo ljholmen)
	(Busline alvsjo fruangen) (Busline fruangen alvsjo)
	(Busline fruangen skarhlmn) (Busline skarhlmn fruangen)	

	(Path kungstrad omalm) (Path omalm kungstrad)	
	(Path tc omalm) (Path omalm tc)
	(Path kungstrad tc) (Path tc kungstrad)
	(Path kungstrad nybroplan) (Path nybroplan kungstrad)
	(Path nybroplan omalm) (Path omalm nybroplan)

  	(At person kista)

	(= (MetroDist kista vskogen) 11) (= (MetroDist vskogen kista) 11)
	(= (MetroDist sdbyberg vskogen) 6) (= (MetroDist vskogen sdbyberg) 6)
	(= (MetroDist tc vskogen) 35) (= (MetroDist vskogen tc) 35)
	(= (MetroDist tc kungstrad) 10) (= (MetroDist kungstrad tc) 10)
	(= (MetroDist tc omalm) 10) (= (MetroDist omalm tc) 10)
	(= (MetroDist uni omalm) 7) (= (MetroDist omalm uni) 7)
	(= (MetroDist ropsten omalm) 6) (= (MetroDist omalm ropsten) 6)
	(= (MetroDist tc ljholmen) 50) (= (MetroDist ljholmen tc) 50)
	(= (MetroDist fruangen ljholmen) 8) (= (MetroDist ljholmen fruangen) 8)
	(= (MetroDist skarhlmn ljholmen) 14) (= (MetroDist ljholmen skarhlmn) 14)
	
	(= (BusDist kista frosunda) 11) (= (BusDist frosunda kista) 11)
	(= (BusDist frosunda skyttehlm) 8) (= (BusDist skyttehlm frosunda) 8)
	(= (BusDist skyttehlm vskogen) 7) (= (BusDist vskogen skyttehlm) 7)
	(= (BusDist vskogen karlberg) 5) (= (BusDist karlberg vskogen) 5)
	(= (BusDist karlberg karlstrnd) 4) (= (BusDist karlstrnd karlberg) 4)
	(= (BusDist karlstrnd omalm) 12) (= (BusDist omalm karlstrnd) 12)
	(= (BusDist omalm nybroplan) 4) (= (BusDist nybroplan omalm) 4)
	(= (BusDist nybroplan kungstrad) 9) (= (BusDist kungstrad nybroplan) 9)
	(= (BusDist kungstrad rosenlund) 36) (= (BusDist rosenlund kungstrad) 36)
	(= (BusDist rosenlund ljholmen) 7) (= (BusDist ljholmen rosenlund) 7)
	(= (BusDist ljholmen alvsjo) 10) (= (BusDist alvsjo ljholmen) 10)
	(= (BusDist alvsjo fruangen) 10) (= (BusDist fruangen alvsjo) 10)
	(= (BusDist fruangen skarhlmn) 14) (= (BusDist skarhlmn fruangen) 14)

	(= (PathDist kungstrad omalm) 11) (= (PathDist omalm kungstrad) 11)
	(= (PathDist omalm tc) 16) (= (PathDist tc omalm) 16)
	(= (PathDist kungstrad tc) 5) (= (PathDist tc kungstrad) 5)
	(= (PathDist kungstrad nybroplan) 6) (= (PathDist nybroplan kungstrad) 6)
	(= (PathDist nybroplan omalm) 7) (= (PathDist omalm nybroplan) 7)

  )
  (:goal (and (At person kungstrad) (Visited ljholmen)))
  
  (:metric minimize (total-cost))
  )
